version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-work-orders
    environment:
      POSTGRES_DB: work-orders
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: